imports_granularity = 'Crate'
tab_spaces = 2
max_width = 200
indent_style = 'Block'
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = 'StdExternalCrate'
use_field_init_shorthand = true
wrap_comments = true
fn_single_line = true
where_single_line = true
brace_style = 'PreferSameLine'